### ISSUE TITLE
音楽が再生できなくなった

### ISSUE THREAD

**Issue by nooneMona** [nooneMona/nitouheDiscordBot#57]
下記流そうとしたらエラー発生
https://www.youtube.com/watch?v=XssXO8IMym8
https://www.youtube.com/watch?v=XssXO8IMym8
https://youtu.be/Uwd7UWSFvNk
https://youtu.be/Uwd7UWSFvNk
https://youtu.be/Uwd7UWSFvNk
https://www.youtube.com/watch?v=RkozLmiLBc0

```
Error: input stream: Status code: 429
    at ClientRequest.<anonymous> (/app/node_modules/miniget/dist/index.js:190:31)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:641:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at TLSSocket.socketOnData (_http_client.js:509:22)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at TLSSocket.Readable.push (internal/streams/readable.js:223:10)
Error: input stream: Status code: 429
    at ClientRequest.<anonymous> (/app/node_modules/miniget/dist/index.js:190:31)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:641:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at TLSSocket.socketOnData (_http_client.js:509:22)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at TLSSocket.Readable.push (internal/streams/readable.js:223:10)
Error: input stream: Status code: 429
    at ClientRequest.<anonymous> (/app/node_modules/miniget/dist/index.js:190:31)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:641:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at TLSSocket.socketOnData (_http_client.js:509:22)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at TLSSocket.Readable.push (internal/streams/readable.js:223:10)
Error: input stream: Status code: 429
    at ClientRequest.<anonymous> (/app/node_modules/miniget/dist/index.js:190:31)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:641:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at TLSSocket.socketOnData (_http_client.js:509:22)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at TLSSocket.Readable.push (internal/streams/readable.js:223:10)
Error: input stream: Status code: 429
    at ClientRequest.<anonymous> (/app/node_modules/miniget/dist/index.js:190:31)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:641:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at TLSSocket.socketOnData (_http_client.js:509:22)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at TLSSocket.Readable.push (internal/streams/readable.js:223:10)
```

[ytdl-core 429 で検索](https://www.google.com/search?sxsrf=ALeKk01upg-4J1ven7aJ2IAm8JBFm8Nk1A%3A1613749484158&ei=7NwvYIySCYOJoATtuYjoCQ&q=ytdl-core+429&oq=ytdl-core+429&gs_lcp=Cgdnd3Mtd2l6EAMyBQgAEMsBOgcIIxCwAxAnOgQIIxAnUO4OWNcSYIwUaAFwAHgAgAG3AYgB8wOSAQMwLjOYAQCgAQGqAQdnd3Mtd2l6yAEBwAEB&sclient=gws-wiz&ved=0ahUKEwiMuImmpfbuAhWDBIgKHe0cAp0Q4dUDCA0&uact=5)すると、出てきそう。

**Comment by iwamizawa-software** [comment]
juke-error-msg

**Comment by nooneMona** [comment]
うむ
